project_id = "vcrjntfjsmpoupgairep"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
port = 54323
ip_version = "ipv6"

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1"
openai_api_key = "env(OPENAI_API_KEY)"

[inbucket]
enabled = true
port = 54324
port_web = 54325

[storage]
enabled = true
port = 54326
file_size_limit = "50MiB"

[auth]
enabled = true
port = 54327
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://127.0.0.1:3000"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
security_update_password_require_reauthentication = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[functions.send-carer-invitation]
verify_jwt = false

[functions.create-system-tenant]
verify_jwt = false

[functions.update-system-tenant]
verify_jwt = false

[functions.delete-system-tenant]
verify_jwt = false

[functions.assign-user-to-organization]
verify_jwt = false

[functions.create-branch-admin]
verify_jwt = false

[functions.news2-ai-recommendations]
verify_jwt = true

[functions.send-password-reset]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.create-organization-member]
verify_jwt = true

[functions.update-organization-member]
verify_jwt = true

[functions.create-service-report-notifications]
verify_jwt = false

[functions.send-notification-email]
verify_jwt = true

[functions.create-third-party-user]
verify_jwt = false

[functions.third-party-login]
verify_jwt = false

[functions.send-event-share-email]
verify_jwt = false

[functions.create-library-resource-notifications]
verify_jwt = false

[functions.create-document-notifications]
verify_jwt = false

[functions.create-form-assignment-notifications]
verify_jwt = false

[functions.create-form-submission-notifications]
verify_jwt = false

[functions.create-agreement-notifications]
verify_jwt = false

[functions.create-training-assignment-notifications]
verify_jwt = false

[functions.create-training-status-update-notifications]
verify_jwt = false

[functions.create-tenant-agreement-notifications]
verify_jwt = false

[functions.process-late-booking-alerts]
verify_jwt = false

[functions.create-expense-notifications]
verify_jwt = false

[functions.create-leave-request-notifications]
verify_jwt = false

[functions.sync-care-plan-data]
verify_jwt = false

[functions.renew-subscription]
verify_jwt = false
